# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
title: Hala Ali Khan
first_name: Hala
middle_name:
last_name: Ali Khan
contact_note:
description: >
  Graduate student in Biomedical Engineering at UNIST. I work on AI for bioimaging:
  virtual staining, explainability, and generative models for pathology.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with
  <a href="https://github.com/alshedivat/al-folio">al-folio</a>. Hosted by GitHub Pages.
keywords: biomedical ai, virtual staining, generative models, microscopy, pathology
lang: en
icon: "🧬"

url: https://HalaKhan00.github.io
baseurl: ""
last_updated: false
back_to_top: true

# -----------------------------------------------------------------------------
# Theme / Layout
# -----------------------------------------------------------------------------
navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: true
posts_in_search: true
bib_search: true
max_width: 930px

serve_og_meta: true
serve_schema_org: false
og_image: /assets/img/portrait.jpg

# -----------------------------------------------------------------------------
# Profile & Links
# -----------------------------------------------------------------------------
github_username: HalaKhan00
email: your@email
scholar_userid: ""     # fill if you have
orcid: ""
twitter_username: ""
enable_navbar_social: true

navbar:
  links:
    - title: About
      url: /
    - title: Publications
      url: /publications/
    - title: News
      url: /news/
    - title: Projects
      url: /projects/
    - title: CV
      url: /cv/
    - title: GitHub
      url: https://github.com/HalaKhan00

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Hala’s Notes
blog_description: AI for bioimaging
permalink: /blog/:year/:title/
pagination:
  enabled: true
related_blog_posts:
  enabled: true
  max_related: 5

# Remove template external feeds for now
external_sources: []

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  books:
    output: true
  news:
    defaults:
      layout: post
    output: true
  projects:
    output: true

# -----------------------------------------------------------------------------
# Jekyll Scholar (your authorship)
# -----------------------------------------------------------------------------
scholar:
  last_name: [Khan]
  first_name: [Hala, H.]
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters: [latex, smallcaps, superscript]
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_link: Details
  query: "@*"
  group_by: year
  group_order: descending

enable_publication_badges:
  altmetric: true
  dimensions: true
  google_scholar: true
  inspirehep: true

filtered_bibtex_keywords:
  [abbr, abstract, additional_info, altmetric, annotation, arxiv, award, award_name,
   bibtex_show, blog, code, google_scholar_id, html, inspirehep_id, pdf, poster,
   preview, selected, slides, supp, video, website]

max_author_limit: 3
enable_publication_thumbnails: true

# Keep the rest of your plugins, imagemagick, libraries, etc. as in your file.
